version: "3.9"

services:
  database:
    image: mysql:5.7
    ports:
      - "63306:3306"
    environment:
      MYSQL_DATABASE: clinical_stud
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root

  php-apache:
    build: ./config/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./aws-resources/scripts/httpd.conf:/etc/httpd/conf/httpd.conf
    environment:
      DB_HOST: database
      DB_NAME: clinical_study
      DB_USER: root
      DB_PASS: root
